app:
  name: "mint"
  mode: "dev"
  port: 8081

snowflake:
  start_time: "2026-07-16"
  machine_id: 1

log:
  level: "debug"
  filename: "mint.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "Accelerator0611!"
  dbname: "mint"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

jwt:
  secret: "我永远喜欢夏天与夕阳"
  access_expire: 15 # 单位：分钟
  refresh_expire: 1 # 单位：天 